### ISSUE TITLE
Alternate Linters

### ISSUE THREAD

**Issue by karai17** [dcr30/vscode-lualinter#1]
While having a luac parser does help with syntax errors, I wouldn't quite call that "linting". Would it be possible to also integrate LuaCheck so that we can not only have valid code, but clean code checks?

Would it also be possible to add an option that allows you to use the LuaJIT parser instead of luac?

**Comment by nbredikhin** [comment]
Currently it doesn't support displaying more than one error, because luac outputs only one error. But it should be easy to fix.

Actually I wanted to use luacheck by default at the beginning, but I had problems with installing and testing it on Windows, so I decided to stick with luac at first. 

But I think it's possible to integrate luacheck, yes.

**Comment by karai17** [comment]
Installing LuaCheck via LuaRocks should be fairly straightforward. I'm not on Windows, but I installed it last night without any issue.

Also, here is some info provided by LuaCheck that's handy to have around:

https://luacheck.readthedocs.io/en/stable/cli.html#stable-interface-for-editor-plugins-and-tools

It would probably be nice to allow users to be able to control how LuaCheck runs in VS Code by defining a few settings; example:

``` typescript
"lualinter.globals = {
    "type": "array",
    "default": [],
    "description": "List of globals for LuaCheck to ignore"
}

"lualinter.globals": [
    "love",
    "jit",
    "ffi"
]
```

**Comment by nbredikhin** [comment]
I think it's not necessary to add these options (globals, etc) to the extension settings. As I know, LuaCheck already automatically loads a [configuration file](https://luacheck.readthedocs.io/en/stable/config.html#configuration-file) from the working directory. Correct me if I'm wrong.

Anyways, I gonna try to implement it in the near future.

**Comment by karai17** [comment]
That's perfect, then. If LuaCheck loads a dot file, that's all that's needed.
