### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by m4xc4v413r4** [dcr30/vscode-lualinter#4]
Hello,

So, I've compiled lua, added the folder where luac.exe is located to PATH and still can't get the linter to work. If I just open a cmd from windows and do luac -p <file> it works, so the compiling was done properly.

Can you help me out? :)

**Comment by nbredikhin** [comment]
Hello. Try installing Lua with this:
https://github.com/rjpcomputing/luaforwindows

If it doesn't help, let me know, I'll take a deeper look then!

**Comment by m4xc4v413r4** [comment]
I can't install using that because I need a very specific version of lua
for my projects.
Where is the extension checking for "luac.exe"? Maybe I can just move it
there so it will pick it up or something.

Thanks again and sorry for the bother.

Em 05/02/2017 14:37, "Nikita Bredikhin" <notifications@github.com> escreveu:

**Comment by m4xc4v413r4** [comment]
Forget about it, just turned on the computer and went to VSC and it's working now for some reason, maybe the turning off/on the pc did it... no idea, it's working now.

**Comment by nbredikhin** [comment]
Probably you forgot to restart VSCode after adding luac to PATH.

**Comment by m4xc4v413r4** [comment]
To tell you the truth I can't say that I did or not because I can't remember, it was already like 3 or 4 am xD

In any case, thanks for this man, I was tiered of wasting time looking for a stupid comma out of place ;)
